// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE2gK4SxExX-vkeHZtYL80tiarfhcqDMU',
    appId: '1:1085838788540:web:f8da9144fa5f4c1132cdb9',
    messagingSenderId: '1085838788540',
    projectId: 'fit-x-cd2c8',
    authDomain: 'fit-x-cd2c8.firebaseapp.com',
    storageBucket: 'fit-x-cd2c8.firebasestorage.app',
    measurementId: 'G-9YFK593Z1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiaXECnI17gk6q6pCF5aNiwGoAawW8Wmk',
    appId: '1:1085838788540:android:162188df6c458c0632cdb9',
    messagingSenderId: '1085838788540',
    projectId: 'fit-x-cd2c8',
    storageBucket: 'fit-x-cd2c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTn_xOcCyHTiJqn2PMDuwaveoWa0Y9CPg',
    appId: '1:1085838788540:ios:953220e2b6e8814232cdb9',
    messagingSenderId: '1085838788540',
    projectId: 'fit-x-cd2c8',
    storageBucket: 'fit-x-cd2c8.firebasestorage.app',
    iosClientId: '1085838788540-m2e17kebq907jmlj9tv63eof07gtsk7t.apps.googleusercontent.com',
    iosBundleId: 'com.fitx.app',
  );

}